app:
  name: myapp
  port: :8080

database:
  dsn: root:123456@qwe@tcp(127.0.0.1:3306)/mygin_db?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenConns: 100

log:
  level: "debug"           # 日志级别: debug, info, warn, error
  filename: "./logs/app.log"  # 日志文件路径
  maxsize: 128           # 每个日志文件保存的最大尺寸 单位：M
  maxbackups: 3         # 日志文件最多保存多少个备份
  maxage: 2             # 文件最多保存多少天
  compress: false        # 是否压缩