basePath: /api
definitions:
  api_v1.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  api_v1.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  api_v1.LoginResponse:
    properties:
      token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server using Gin framework.
  title: MyGin API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: Login Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api_v1.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_v1.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api_v1.ErrorResponse'
      summary: User Login
      tags:
      - auth
swagger: "2.0"
